### ISSUE TITLE
Can the validation work on models returned from a computed

### ISSUE THREAD

**Issue by T-Roth** [deulos/vuejs-model-validator#12]
Can the validation work on models returned from a computed?

**Comment by ragnarlotus** [comment]
If i tell you the truth I didnt test it but it should

**Comment by T-Roth** [comment]
I've been unable to get it working with a model returned from a computed, it seems like the validations do not get applied.

**Comment by T-Roth** [comment]
I get errors when calling .validate and if I include $error in the markup it errors

**Comment by ragnarlotus** [comment]
Probably the computed removes the validator internal variables but I will take note and think a way to do it for next versions :)

**Comment by ragnarlotus** [comment]
I am preparing a full rework of the component using full ES6 syntax with classes, proxies and other stuff. This way will be much more powerful, and easy to develop.

I didn't reach the computed properties so I can't tell you yet if it is possible, but if you have any other ideas of enhacements and improvements is a good moment contribute :)

**Comment by T-Roth** [comment]
Some other ideas:

1.) Conditional validation.   Might need to make a field being required conditional based on another field (could possibly apply to other validations rules as well)

2.) Would be nice if there was a way to inject a friendly field name into the validation messages.  
ex: `validationMessages: {
   required: '{friendlyFieldName} is required',`

3.) Generic way to get a summary of validation errors. 
ex: `$vmv.user.$errors`
I would like to show a list of all errors to a user when they try to submit, but it would need to have the friendly name from above for it to make sense


4.) Would be nice if I could get a list of validations applied to a field
ex: `$vmv.user.email.required`
The reason I want this is so I can create component for each form input control type (text, checkbox, select...) and pass in if is required and the current error message as params so the component can show it. My models and validation schema are going to be autogenerated, so I don't want to hardcode anything.

Thanks

**Comment by ragnarlotus** [comment]
New version almost ready 😃 

If I didn't understand you wrong, includes all features you requested, even computed.

Unfortunally it is not compatible with current version as the new version is built on top of ES6, this means classes, proxies, maps, destructuring etc. This means that the validator has brand new architecture , clear, easy to understand and hopefully more open to contributing.

I also decided to chage its name, as the owner of vue-model-validator ignored my messages trying to transfer me the package name (abandoned for more than 3 years) so the new version will be called [vue-daval](https://github.com/deulos/vue-daval) which I like and is shorter (vue-DAtaVALidator) hehehe.

I'll let you know once the docs are updated so in case you want to give it a try, you can send me comments and some feedback.

Really appreciate your time and comments.

Best regards!

**Comment by T-Roth** [comment]
Thanks for the update, I look forward to trying it out.

**Comment by ragnarlotus** [comment]
Hello, I presume the new data validator is finished.

You cand head to https://github.com/deulos/vue-daval to try it out! :)

It has many improvements and enhacements that other validators don't have.

Regards!
