### ISSUE TITLE
Is there a way to register my own custom validation functions with the built in list

### ISSUE THREAD

**Issue by T-Roth** [deulos/vuejs-model-validator#13]
Is there a way to register my own custom validation functions with the built in list?

I know I can add them to the validation schema for a model on the fly but it would be nice if there was a way to add to the built in list

**Comment by ragnarlotus** [comment]
No sorry, I take note and add it to next release :)

**Comment by ragnarlotus** [comment]
Hello! there is a new relase allowing you to add your custom validators :)

I will update the docs now.

https://github.com/deulos/vuejs-model-validator/wiki/Custom-validation

Don't hesitate to propose more enhacements!
