### ISSUE TITLE
Error with validationMessages in beforeMount

### ISSUE THREAD

**Issue by iowahc** [deulos/vuejs-model-validator#14]
validationMessages are not applied to this.$vmv.messages when used in Component Declaration.

Code failing is in vuejs-model-validator/src/components/index.js:30
`if (this.$options.validationMessages) this.vmv.setMessages(this.$options.validationMessages);`
should either be
`if (this.$options.validationMessages) this.$vmv.$setMessages(this.$options.validationMessages);`
or 
`if (this.$options.validationMessages) vmv.setMessages(this.$options.validationMessages);`

Could you check this please?

**Comment by ragnarlotus** [comment]
Sure, I will make a new release today or tomorrow top.

Thanks a lot for reporting!

**Comment by ragnarlotus** [comment]
Fixed, thank you!
