### ISSUE TITLE
Using intput text control with numeric validation fails

### ISSUE THREAD

**Issue by T-Roth** [deulos/vuejs-model-validator#15]
I'm having an issue with the numeric validation failing for input fields, it seems the value is being converted to a string and fails the validation.

**Comment by ragnarlotus** [comment]
Yes, inputs defaults type to string.

Use `v-model.number="varName"` to convert it to number automatically

**Comment by T-Roth** [comment]
Thanks, that fixed it.

Still learning Vue :)
